export const componentThemeConfig = {
  blue: {
    "white-color-button": "whiteBlue",
    'hover-background': "hover:bg-blue-50/40",
    'before-text-color': "before:text-blue-600",
    'text-color': "text-blue-600",
    'light-text-color': "text-blue-200",
    'background-color': "bg-blue-600",
    'background-color-trans': "bg-blue-600/20",
    'light-background-color': "bg-blue-50",
    'border-color': "border-blue-600",
    'fill-color': 'fill-blue-500',
    'darker-fill-color': 'fill-blue-600',
    'light-fill-color': 'fill-blue-300',
    'dark-text-hover': 'hover:text-blue-800',
    'ring-color': 'ring-blue-600',
  },
  red: {
    "white-color-button": "whiteRed",
    'hover-background': "hover:bg-red-50/40",
    'before-text-color': "before:text-red-600",
    'text-color': "text-red-600",
    'light-text-color': "text-red-200",
    'background-color': "bg-red-600",
    'background-color-trans': "bg-red-600/20",
    'light-background-color': "bg-red-50",
    'border-color': "border-red-600",
    'fill-color': 'fill-red-500',
    'darker-fill-color': 'fill-red-600',
    'light-fill-color': 'fill-red-300',
    'dark-text-hover': 'hover:text-red-800',
    'ring-color': 'ring-red-600',
  },
  green: {
    "white-color-button": "whiteGreen",
    'hover-background': "hover:bg-emerald-50/40",
    'before-text-color': "before:text-emerald-600",
    'text-color': "text-emerald-600",
    'light-text-color': "text-emerald-200",
    'background-color': "bg-emerald-600",
    'background-color-trans': "bg-emerald-600/20",
    'light-background-color': "bg-emerald-50",
    'border-color': "border-emerald-600",
    'fill-color': 'fill-emerald-500',
    'darker-fill-color': 'fill-emerald-600',
    'light-fill-color': 'fill-emerald-300',
    'dark-text-hover': 'hover:text-emerald-800',
    'ring-color': 'ring-emerald-600',
  },
  gold: {
    "white-color-button": "whiteGold",
    'hover-background': "hover:bg-amber-50/40",
    'before-text-color': "before:text-amber-600",
    'text-color': "text-amber-600",
    'light-text-color': "text-amber-200",
    'background-color': "bg-amber-600",
    'background-color-trans': "bg-amber-600/20",
    'light-background-color': "bg-amber-50",
    'border-color': "border-amber-600",
    'fill-color': 'fill-amber-500',
    'darker-fill-color': 'fill-amber-600',
    'light-fill-color': 'fill-amber-300',
    'dark-text-hover': 'hover:text-amber-800',
    'ring-color': 'ring-amber-600',
  }

}